#!/bin/bash

# Colors

bold='\033[1m' # Bold Text

black='\033[30m'
white='\033[37m'
cyan='\033[36m'

red='\033[41m' # HighLight
hcyan='\033[46m' # HighLight

reset='\033[0m' # Reset Colors

## Start Android Debug Bridge

adb start-server



user=$USER # Get User of system


echo -e """$white



	██╗  ██╗██╗   ██╗ ██████╗ ███╗   ██╗██╗   ██╗███████╗     █████╗ ███╗   ██╗██████╗ ██████╗  ██████╗ ██╗██████╗ 
	██║ ██╔╝╚██╗ ██╔╝██╔════╝ ████╗  ██║██║   ██║██╔════╝    ██╔══██╗████╗  ██║██╔══██╗██╔══██╗██╔═══██╗██║██╔══██╗
	█████╔╝  ╚████╔╝ ██║  ███╗██╔██╗ ██║██║   ██║███████╗    ███████║██╔██╗ ██║██║  ██║██████╔╝██║   ██║██║██║  ██║
	██╔═██╗   ╚██╔╝  ██║   ██║██║╚██╗██║██║   ██║╚════██║    ██╔══██║██║╚██╗██║██║  ██║██╔══██╗██║   ██║██║██║  ██║
	██║  ██╗   ██║   ╚██████╔╝██║ ╚████║╚██████╔╝███████║    ██║  ██║██║ ╚████║██████╔╝██║  ██║╚██████╔╝██║██████╔╝
	╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝ ╚══════╝    ╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝╚═════╝ 
														       
			███████╗ ██████╗ █████╗ ███╗   ██╗███╗   ██╗███████╗██████╗                                    
			██╔════╝██╔════╝██╔══██╗████╗  ██║████╗  ██║██╔════╝██╔══██╗                                   
			███████╗██║     ███████║██╔██╗ ██║██╔██╗ ██║█████╗  ██████╔╝                                   
			╚════██║██║     ██╔══██║██║╚██╗██║██║╚██╗██║██╔══╝  ██╔══██╗                                   
			███████║╚██████╗██║  ██║██║ ╚████║██║ ╚████║███████╗██║  ██║                                   
			╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝                                   
														       


                                                                                                                                                                               

$reset"""



FILE_PATH="/home/$user/L4A"

if [ -d "$FILE_PATH" ];then
	true
else
	mkdir /home/$user/L4A
fi





menu(){


	echo -e "$white$bold [ 1 ] Scan $reset"
	echo -e "$white$bold [ 2 ] Analyze Meticulously $reset"
	echo -e "$white$bold [ 3 ] Save Device Info $reset "
	echo -e "$white$bold [ 4 ] Expert Mode $reset "
	echo -e "$white$bold [ 5 ] Exit  $reset\n"


	printf "$white$bold ➜  ~  $reset"
	read response

	if [ "$response" == 1 ];then

	scan_start_time=`date "+%Y/%m/%d-%H:%M:%S"`
		scan
		scan2
	elif [ "$response" == 2 ];then
		am
	elif [ "$response" == 3 ];then
		info
	elif [ "$response" == 4 ];then
		expert
	elif [ "$response" == 5 ];then
		echo -e "$red$white$bold EXIT "
		exit
	else
		echo -e "$red$white$bold !!! Please Enter Valid Number $reset"
		menu
	fi



}


devices=` adb devices  | grep -w device`
if [ "$devices" ];then
	serial=`adb get-serialno`
	state=`adb get-state`
	dev_path=`adb get-devpath`
	
	echo -e "$cyan ======= Device Information ======="
	echo -e "$cyan Serial : $serial"
	echo -e "$cyan State :  $state"
	echo -e "$cyan Device Path : $dev_path $reset"
	echo -e "$cyan ================================== $reset"

else
	echo -e "$red$white No Device Detected [ ERROR ] "
	exit 0
fi





scan(){


## Basic Database of app:
## https://www.forbes.com/sites/zakdoffman/2019/12/19/avoid-these-100-android-apps-hiding-malicious-malware-new-fraud-arms-race-underway/?sh=372645f539e8

	ports=`adb shell netstat -na | grep -w LISTEN | cut -d":" -f2 | cut -d " " -f1  | grep -o "[0-9]*"`
	
	echo -e "$red$white OpenPorts : $reset"
	for port in $ports;do
		echo "Port : $port"
	done

	
	
	echo -e "$white$bold ========== Engine1: Start Scan with Zak Doffman Info ========== $reset"
	sleep 2

	files=`adb shell pm list packages | cut -d ":" -f2`
	sdpackfiles=`adb shell ls /sdcard/Android/data`


	for file in $files;do
		if [ "$file" == "com.false.call.trick" ] || \
			[ "$file" == "yourdestinypredict.yourlifetest.amazingma gic" ] || \
			[ "$file" == "magicball.funnyapp.useful.crystal" ] || \
			[ "$file" == "com.false.call.trick" ] || \
			[ "$file" == "com.daily.best.suit.you" ] || \
			[ "$file" == "com.personal.fortune.text" ] || \
			[ "$file" == "com.frank.video.call.lite.pro.prank" ] || \
			[ "$file" == "bedtime.reminder.lite.sleep" ] || \
			[ "$file" == "com.ssdk.test" ] || \
			[ "$file" == "your.best.lucky.master.test.new" ] || \
			[ "$file" == "well.sleep.guard.relax" ] || \
			[ "$file" == "test.you.romantic.quize" ] || \
			[ "$file" == "super.lucky.magican.newest" ] || \
			[ "$file" == "relax.ezzz.sleep.cradle" ] || \
			[ "$file" == "pic.art.photo.studio.picture" ] || \
			[ "$file" == "photo.editor.pro.magic" ] || \
			[ "$file" == "nmd.android.test.what.suitable" ] || \
			[ "$file" == "nmd.android.scanner.master.plus" ] || \
			[ "$file" == "nmd.android.multiple.fortune.test" ] || \
			[ "$file" == "nmd.android.location.faker.master" ] || \
			[ "$file" == "nmd.android.good.luck.everyday" ] || \
			[ "$file" == "nmd.android.fake.incoming.call" ] || \
			[ "$file" == "nmd.android.clam.white.noise" ] || \
			[ "$file" == "nmd.android.better.fortune.signs" ] || \
			[ "$file" == "nmd.android.best.fortune.explorer" ] || \
			[ "$file" == "nmd.andriod.mobile.calculator.master" ] || \
			[ "$file" == "nmd.andriod.better.calculator.plus" ] || \
			[ "$file" == "newest.android.fake.location.changer" ] || \
			[ "$file" == "my.lucky.goddness.today.test" ] || \
			[ "$file" == "mobi.clock.android" ] || \
			[ "$file" == "good.lucky.is.coming.hh" ] || \
			[ "$file" == "com.word.fun.level.english" ] || \
			[ "$file" == "com.wmmaster.android" ] || \
			[ "$file" == "com.tiny.scanner.tool.nmd" ] || \
			[ "$file" == "com.test.lover.match" ] || \
			[ "$file" == "com.test.fortune.tester" ] || \
			[ "$file" == "com.test.find.your.love" ] || \
			[ "$file" == "com.smart.scanner.master.nmd" ] || \
			[ "$file" == "com.sleeptimer.android" ] || \
			[ "$file" == "com.sleepassistantool.android" ] || \
			[ "$file" == "com.sleep.in.rain" ] || \
			[ "$file" == "com.sleep.comfortable.sounds" ] || \
			[ "$file" == "com.simple.days.counter" ] || \
			[ "$file" == "com.scan.code.tool" ] || \
			[ "$file" == "com.puzzle.cute.dog.android" ] || \
			[ "$file" == "com.pro.test.noise" ] || \
			[ "$file" == "com.phonecallmaker.android" ] || \
			[ "$file" == "com.prank.call.fake.ring" ] || \
			[ "$file" == "com.pocker.pro.mobile.mirror" ] || \
			[ "$file" == "com.phone.mirror.pro" ] || \
			[ "$file" == "com.phone.lite.frame" ] || \
			[ "$file" == "com.non.stop.writing" ] || \
			[ "$file" == "com.nomophotoeditor.android" ] || \
			[ "$file" == "com.nice.mobile.mirror.hd" ] || \
			[ "$file" == "com.nanny.tool.data" ] || \
			[ "$file" == "com.my.pocker.mobile.mirror" ] || \
			[ "$file" == "com.my.constellation.love.work" ] || \
			[ "$file" == "com.my.big.days.counter" ] || \
			[ "$file" == "com.multiple.scanner.plus.nmd" ] || \
			[ "$file" == "com.math.puzzles.riddle.braingame" ] || \
			[ "$file" == "com.math.iq.puzzle.riddle.braingame" ] || \
			[ "$file" == "com.math.braingame.puzzle.riddle" ] || \
			[ "$file" == "com.magnifying.glass.tool" ] || \
			[ "$file" == "com.lucky.destiny.teller" ] || \
			[ "$file" == "com.lucky.charm.text" ] || \
			[ "$file" == "com.love.yourself.women" ] || \
			[ "$file" == "com.lovetest.plus.android" ] || \
			[ "$file" == "com.lite.fake.gps.location" ] || \
			[ "$file" == "com.led.color.light.rolling" ] || \
			[ "$file" == "com.isleep.cycleclock.android" ] || \
			[ "$file" == "com.instanomo.android" ] || \
			[ "$file" == "com.important.days.matter" ] || \
			[ "$file" == "com.idays.dayscounter.android" ] || \
			[ "$file" == "com.ice.survival.berg" ] || \
			[ "$file" == "com.game.color.hunter" ] || \
			[ "$file" == "com.funny.word.game.english" ] || \
			[ "$file" == "com.funny.lie.truth.detector" ] || \
			[ "$file" == "com.free.lucky.prediction.test" ] || \
			[ "$file" == "com.free.code.scanner.nmd" ] || \
			[ "$file" == "com.frank.video.call.lite" ] || \
			[ "$file" == "com.frame.easy.phone" ] || \
			[ "$file" == "com.find.you.lover.test" ] || \
			[ "$file" == "com.find.difference.detective.little" ] || \
			[ "$file" == "com.filemanagerzeropro.android" ] || \
			[ "$file" == "com.filemanageryo.android" ] || \
			[ "$file" == "com.filemanagerupro.android" ] || \
			[ "$file" == "com.filemanagerkilopro.android" ] || \
			[ "$file" == "com.fast.code.scanner.nmd" ] || \
			[ "$file" == "com.fancy.lovetest.android" ] || \
			[ "$file" == "com.false.location" ] || \
			[ "$file" == "com.fake.caller.plus" ] || \
			[ "$file" == "com.fakecaller.android" ] || \
			[ "$file" == "com.fake.call.girlfriend.prank2019" ] || \
			[ "$file" == "com.ezzz.fan.sleep.noise" ] || \
			[ "$file" == "com.drink.water.remind.you" ] || \
			[ "$file" == "com.dog.bark.picture.puzzle" ] || \
			[ "$file" == "com.dodge.emoji.game" ] || \
			[ "$file" == "com.detector.noise.tool" ] || \
			[ "$file" == "com.days.remind.calendar" ] || \
			[ "$file" == "com.days.daysmatter365.android" ] || \
			[ "$file" == "com.data.securite.data" ] || \
			[ "$file" == "com.dangerous.writing.note" ] || \
			[ "$file" == "com.dailycostmaster.android" ] || \
			[ "$file" == "com.daily.wonderfull.moment" ] || \
			[ "$file" == "com.cute.love.test.android" ];then
				echo -e "$red $file Find Malware $reset"
		else
				printf "$white$bold $file$reset\t$cyan\t\t\t\t\t [ OK ] $reset\n"
				sleep 0.1
		fi
	done



	echo -e "$white$bold  ========== Start Scan SDcard Packages ========== $reset"
	sleep 2
	for sdfile in $sdpackfiles;do
		if [ "$sdfile" == "com.false.call.trick" ] || \
			[ "$sdfile" == "yourdestinypredict.yourlifetest.amazingma gic" ] || \
			[ "$sdfile" == "magicball.funnyapp.useful.crystal" ] || \
			[ "$sdfile" == "com.false.call.trick" ] || \
			[ "$sdfile" == "com.daily.best.suit.you" ] || \
			[ "$sdfile" == "com.personal.fortune.text" ] || \
			[ "$sdfile" == "com.frank.video.call.lite.pro.prank" ] || \
			[ "$sdfile" == "bedtime.reminder.lite.sleep" ] || \
			[ "$sdfile" == "com.ssdk.test" ] || \
			[ "$sdfile" == "your.best.lucky.master.test.new" ] || \
			[ "$sdfile" == "well.sleep.guard.relax" ] || \
			[ "$sdfile" == "test.you.romantic.quize" ] || \
			[ "$sdfile" == "super.lucky.magican.newest" ] || \
			[ "$sdfile" == "relax.ezzz.sleep.cradle" ] || \
			[ "$sdfile" == "pic.art.photo.studio.picture" ] || \
			[ "$sdfile" == "photo.editor.pro.magic" ] || \
			[ "$sdfile" == "nmd.android.test.what.suitable" ] || \
			[ "$sdfile" == "nmd.android.scanner.master.plus" ] || \
			[ "$sdfile" == "nmd.android.multiple.fortune.test" ] || \
			[ "$sdfile" == "nmd.android.location.faker.master" ] || \
			[ "$sdfile" == "nmd.android.good.luck.everyday" ] || \
			[ "$sdfile" == "nmd.android.fake.incoming.call" ] || \
			[ "$sdfile" == "nmd.android.clam.white.noise" ] || \
			[ "$sdfile" == "nmd.android.better.fortune.signs" ] || \
			[ "$sdfile" == "nmd.android.best.fortune.explorer" ] || \
			[ "$sdfile" == "nmd.andriod.mobile.calculator.master" ] || \
			[ "$sdfile" == "nmd.andriod.better.calculator.plus" ] || \
			[ "$sdfile" == "newest.android.fake.location.changer" ] || \
			[ "$sdfile" == "my.lucky.goddness.today.test" ] || \
			[ "$sdfile" == "mobi.clock.android" ] || \
			[ "$sdfile" == "good.lucky.is.coming.hh" ] || \
			[ "$sdfile" == "com.word.fun.level.english" ] || \
			[ "$sdfile" == "com.wmmaster.android" ] || \
			[ "$sdfile" == "com.tiny.scanner.tool.nmd" ] || \
			[ "$sdfile" == "com.test.lover.match" ] || \
			[ "$sdfile" == "com.test.fortune.tester" ] || \
			[ "$sdfile" == "com.test.find.your.love" ] || \
			[ "$sdfile" == "com.smart.scanner.master.nmd" ] || \
			[ "$sdfile" == "com.sleeptimer.android" ] || \
			[ "$sdfile" == "com.sleepassistantool.android" ] || \
			[ "$sdfile" == "com.sleep.in.rain" ] || \
			[ "$sdfile" == "com.sleep.comfortable.sounds" ] || \
			[ "$sdfile" == "com.simple.days.counter" ] || \
			[ "$sdfile" == "com.scan.code.tool" ] || \
			[ "$sdfile" == "com.puzzle.cute.dog.android" ] || \
			[ "$sdfile" == "com.pro.test.noise" ] || \
			[ "$sdfile" == "com.phonecallmaker.android" ] || \
			[ "$sdfile" == "com.prank.call.fake.ring" ] || \
			[ "$sdfile" == "com.pocker.pro.mobile.mirror" ] || \
			[ "$sdfile" == "com.phone.mirror.pro" ] || \
			[ "$sdfile" == "com.phone.lite.frame" ] || \
			[ "$sdfile" == "com.non.stop.writing" ] || \
			[ "$sdfile" == "com.nomophotoeditor.android" ] || \
			[ "$sdfile" == "com.nice.mobile.mirror.hd" ] || \
			[ "$sdfile" == "com.nanny.tool.data" ] || \
			[ "$sdfile" == "com.my.pocker.mobile.mirror" ] || \
			[ "$sdfile" == "com.my.constellation.love.work" ] || \
			[ "$sdfile" == "com.my.big.days.counter" ] || \
			[ "$sdfile" == "com.multiple.scanner.plus.nmd" ] || \
			[ "$sdfile" == "com.math.puzzles.riddle.braingame" ] || \
			[ "$sdfile" == "com.math.iq.puzzle.riddle.braingame" ] || \
			[ "$sdfile" == "com.math.braingame.puzzle.riddle" ] || \
			[ "$sdfile" == "com.magnifying.glass.tool" ] || \
			[ "$sdfile" == "com.lucky.destiny.teller" ] || \
			[ "$sdfile" == "com.lucky.charm.text" ] || \
			[ "$sdfile" == "com.love.yourself.women" ] || \
			[ "$sdfile" == "com.lovetest.plus.android" ] || \
			[ "$sdfile" == "com.lite.fake.gps.location" ] || \
			[ "$sdfile" == "com.led.color.light.rolling" ] || \
			[ "$sdfile" == "com.isleep.cycleclock.android" ] || \
			[ "$sdfile" == "com.instanomo.android" ] || \
			[ "$sdfile" == "com.important.days.matter" ] || \
			[ "$sdfile" == "com.idays.dayscounter.android" ] || \
			[ "$sdfile" == "com.ice.survival.berg" ] || \
			[ "$sdfile" == "com.game.color.hunter" ] || \
			[ "$sdfile" == "com.funny.word.game.english" ] || \
			[ "$sdfile" == "com.funny.lie.truth.detector" ] || \
			[ "$sdfile" == "com.free.lucky.prediction.test" ] || \
			[ "$sdfile" == "com.free.code.scanner.nmd" ] || \
			[ "$sdfile" == "com.frank.video.call.lite" ] || \
			[ "$sdfile" == "com.frame.easy.phone" ] || \
			[ "$sdfile" == "com.find.you.lover.test" ] || \
			[ "$sdfile" == "com.find.difference.detective.little" ] || \
			[ "$sdfile" == "com.sdfilemanagerzeropro.android" ] || \
			[ "$sdfile" == "com.sdfilemanageryo.android" ] || \
			[ "$sdfile" == "com.sdfilemanagerupro.android" ] || \
			[ "$sdfile" == "com.sdfilemanagerkilopro.android" ] || \
			[ "$sdfile" == "com.fast.code.scanner.nmd" ] || \
			[ "$sdfile" == "com.fancy.lovetest.android" ] || \
			[ "$sdfile" == "com.false.location" ] || \
			[ "$sdfile" == "com.fake.caller.plus" ] || \
			[ "$sdfile" == "com.fakecaller.android" ] || \
			[ "$sdfile" == "com.fake.call.girlfriend.prank2019" ] || \
			[ "$sdfile" == "com.ezzz.fan.sleep.noise" ] || \
			[ "$sdfile" == "com.drink.water.remind.you" ] || \
			[ "$sdfile" == "com.dog.bark.picture.puzzle" ] || \
			[ "$sdfile" == "com.dodge.emoji.game" ] || \
			[ "$sdfile" == "com.detector.noise.tool" ] || \
			[ "$sdfile" == "com.days.remind.calendar" ] || \
			[ "$sdfile" == "com.days.daysmatter365.android" ] || \
			[ "$sdfile" == "com.data.securite.data" ] || \
			[ "$sdfile" == "com.dangerous.writing.note" ] || \
			[ "$sdfile" == "com.dailycostmaster.android" ] || \
			[ "$sdfile" == "com.daily.wonderfull.moment" ] || \
			[ "$sdfile" == "com.cute.love.test.android" ];then
				echo -e "$red $sdfile Find Malware $reset"
		else
				printf "$white$bold $sdfile$reset\t$cyan\t\t\t\t\t [ OK ] $reset\n"
				sleep 0.1
		fi
	done


}


scan2(){

#  Bitdefender 

	echo -e "$white$bold ========== Engine2: Start Scan with  Dr. Web Info ========== $reset \n"
	sleep 2
	packages=`adb shell pm list packages | cut -d ":" -f2`

	sdpack=`adb shell ls /sdcard/Android/data`

	echo -e "$white$bold Start Scan System Packages : $reset"
	for package in $packages;do
		Walls_Light=`echo $package | egrep -E "Walls.*Light"`
		walls_light=`echo $package | egrep -E "walls.*light"`
		Big_Emogi=`echo $package | egrep -E "Big.*Emoji"`
		big_emogi=`echo $package | egrep -E "bi.*emoji"`
		Grad_Wall=`echo $package | egrep -E "Grad.*Wallpaper"`
		grad_wall=`echo $package | egrep -E "grad.*wallpaper"`
		engine_wall=`echo $package | egrep -E "Engine.*Wallpapers"`
		Engine_Wall=`echo $package | egrep -E "engine.*wallpapers"`
		stock_wall=`echo $package | egrep -E "stock.*wallpaper"`
		Stock_Wall=`echo $package | egrep -E "Stock.*Wallpaper"`
		EffectMania=`echo $package | egrep -E "EffectMania"`
		effectmania=`echo $package | egrep -E "effectmania"`
		deep_photoeffect=`echo $package | egrep -E "deep.*photoeffect"`
		Deep_Photoeffect=`echo $package | egrep -E "Deep.*Photoeffect"`
		sticker_whatsapp=`echo $package | egrep -E "Create.*Sticker.*Whatsapp"`
		Sticker_Whatsapp=`echo $package | egrep -E "Deep.*Photoeffect"`
		blur_image=`echo $package | egrep -E "blur.*image"`
		Blur_Image=`echo $package | egrep -E "Blur.*Image"`
		cut_paste=`echo $package | egrep -E "cut.*paste"`
		Cut_Paste=`echo $package | egrep -E "Cut.*Paste"`
		Neon_Theme_Keyboard=`echo $package | egrep -E "Neon.*Theme.*Keyboard"`
		neon_theme_keyboard=`echo $package | egrep -E "neon.*theme.*keyboard"`
		cash_cleaner=`echo $package | egrep -E "cash.*cleaner"`
		Cash_Cleaner=`echo $package | egrep -E "Cash.*Cleaner"`
		Fast_Cleaner=`echo $package | egrep -E "Fast.*Cleaner"`
		fast_cleaner=`echo $package | egrep -E "fast.*cleaner"`
		call_skins=`echo $package | egrep -E "call.*skins"`
		Call_Skins=`echo $package | egrep -E "Call.*Skins"`
		Funny_Caller=`echo $package | egrep -E "Funny.*Calller"`
		funny_caller=`echo $package | egrep -E "funny.*caller"`
		CallME=`echo $package | egrep -E "callme"`
		callme=`echo $package | egrep -E "CallMe"`
		InCall=`echo $package | egrep -E "InCall"`
		incall=`echo $package | egrep -E "incall"`
		mycall=`echo $package | egrep -E "mycall"`
		MyCall=`echo $package | egrep -E "MyCall"`
		NewScrean=`echo $package | egrep -E "NewScrean"`
		newscrean=`echo $package | egrep -E "newscrean"`

		

		if [ "$Walls_Light" == "Walls Light" ] || [ "$wall_light" == "walls light" ] || \
			[ "$Big_Emogi" == "Big Emoji" ] || [ "$big_emogi" == "big emoji" ] || \
			[ "$Grad_Wall" == "Grad Wallpaper" ] || [ "$grad_wall" == "grad wallpaper" ] || \
			[ "$engine_wall" == "Engine Wallpaper" ] || [ "$Engine_Wall" == "engine wallpapaer" ] || \
			[ "$stock_wall" == "stock wallpaper" ] || [ "$Stock_Wall" == "Stock Wallpaper" ] || \
			[ "$EffectMania" == "EffectMania" ] || [ "$effectmania" == "effectmania" ] || \
			[ "$deep_photoeffect" == "Deep Photoeffect" ] || [ "$Deep_Photoeffect" == "deep photoeffect" ] || \
			[ "$sticker_whatsapp" == "sticker whatsapp" ] || [ "$Sticker_Whatsapp" == "Sticker Whatsapp" ] || \
			[ "$blur_image" == "blur image" ] || [ "$Blur_Image" == "Blur Image" ] || \
			[ "$cut_paste" == "cut paste" ] || [ "$Cut_Paste" == "Cut Paste" ] || \
			[ "$Neon_Theme_Keyboard" == "Neon Theme Keyboard" ] || [ "$neon_theme_keyboard" == "neon theme keyboard" ] || \
			[ "$cash_cleaner" == "Cash Cleaner" ] || [ "$Cash_Cleaner" == "cash cleaner" ] || \
			[ "$fast_cleaner" == "Fast Cleaner" ] || [ "$Fast_Cleaner" == "fast clener" ] || \
			[ "$call_skins" == "call skins" ] || [ "$Call_Skins" == "Call Skins" ] || \
			[ "$Funny_Caller" == "Funny Caller" ] || [ "$funny_caller" == "funny caller" ] || \
			[ "$CallME" == "CallMe" ] || [ "$callme" == "callme" ] || \
			[ "$InCall" == "incall" ] || [ "$incall" == "incall" ] || \
			[ "$mycall" == "mycall" ] || [ "$MyCall" == "MyCall" ] || \
			[ "$NewScrean" == "New Screen" ] || [ "$newscrean" == "new screen" ];then

				echo -e "$white$bold $package \t\t\t\t\t\t $red$white [ Malware ] $reset"

		else

				echo -e "$white$bold $package\t\t\t\t\t\t $cyan [ OK ] $reset"
				
		fi
	done

	
	echo -e "$white$bold  ========== Start Scan SDcard Packages ========== $reset"
	sleep 2
	for p in $sdpack;do
		Walls_Light=`echo $p | egrep -E "Walls.*Light"`
		walls_light=`echo $p | egrep -E "walls.*light"`
		Big_Emogi=`echo $p | egrep -E "Big.*Emoji"`
		big_emogi=`echo $p | egrep -E "bi.*emoji"`
		Grad_Wall=`echo $p | egrep -E "Grad.*Wallpaper"`
		grad_wall=`echo $p | egrep -E "grad.*wallpaper"`
		engine_wall=`echo $p | egrep -E "Engine.*Wallpapers"`
		Engine_Wall=`echo $p | egrep -E "engine.*wallpapers"`
		stock_wall=`echo $p | egrep -E "stock.*wallpaper"`
		Stock_Wall=`echo $p | egrep -E "Stock.*Wallpaper"`
		EffectMania=`echo $p | egrep -E "EffectMania"`
		effectmania=`echo $p | egrep -E "effectmania"`
		deep_photoeffect=`echo $p | egrep -E "deep.*photoeffect"`
		Deep_Photoeffect=`echo $p | egrep -E "Deep.*Photoeffect"`
		sticker_whatsapp=`echo $p | egrep -E "Create.*Sticker.*Whatsapp"`
		Sticker_Whatsapp=`echo $p | egrep -E "Deep.*Photoeffect"`
		blur_image=`echo $p | egrep -E "blur.*image"`
		Blur_Image=`echo $p | egrep -E "Blur.*Image"`
		cut_paste=`echo $p | egrep -E "cut.*paste"`
		Cut_Paste=`echo $p | egrep -E "Cut.*Paste"`
		Neon_Theme_Keyboard=`echo $p | egrep -E "Neon.*Theme.*Keyboard"`
		neon_theme_keyboard=`echo $p | egrep -E "neon.*theme.*keyboard"`
		cash_cleaner=`echo $p | egrep -E "cash.*cleaner"`
		Cash_Cleaner=`echo $p | egrep -E "Cash.*Cleaner"`
		Fast_Cleaner=`echo $p | egrep -E "Fast.*Cleaner"`
		fast_cleaner=`echo $p | egrep -E "fast.*cleaner"`
		call_skins=`echo $p | egrep -E "call.*skins"`
		Call_Skins=`echo $p | egrep -E "Call.*Skins"`
		Funny_Caller=`echo $p | egrep -E "Funny.*Calller"`
		funny_caller=`echo $p | egrep -E "funny.*caller"`
		CallME=`echo $p | egrep -E "callme"`
		callme=`echo $p | egrep -E "CallMe"`
		InCall=`echo $p | egrep -E "InCall"`
		incall=`echo $p | egrep -E "incall"`
		mycall=`echo $p | egrep -E "mycall"`
		MyCall=`echo $p | egrep -E "MyCall"`
		NewScrean=`echo $p | egrep -E "NewScrean"`
		newscrean=`echo $p | egrep -E "newscrean"`

		

		if [ "$Walls_Light" == "Walls Light" ] || [ "$wall_light" == "walls light" ] || \
			[ "$Big_Emogi" == "Big Emoji" ] || [ "$big_emogi" == "big emoji" ] || \
			[ "$Grad_Wall" == "Grad Wallpaper" ] || [ "$grad_wall" == "grad wallpaper" ] || \
			[ "$engine_wall" == "Engine Wallpaper" ] || [ "$Engine_Wall" == "engine wallpapaer" ] || \
			[ "$stock_wall" == "stock wallpaper" ] || [ "$Stock_Wall" == "Stock Wallpaper" ] || \
			[ "$EffectMania" == "EffectMania" ] || [ "$effectmania" == "effectmania" ] || \
			[ "$deep_photoeffect" == "Deep Photoeffect" ] || [ "$Deep_Photoeffect" == "deep photoeffect" ] || \
			[ "$sticker_whatsapp" == "sticker whatsapp" ] || [ "$Sticker_Whatsapp" == "Sticker Whatsapp" ] || \
			[ "$blur_image" == "blur image" ] || [ "$Blur_Image" == "Blur Image" ] || \
			[ "$cut_paste" == "cut paste" ] || [ "$Cut_Paste" == "Cut Paste" ] || \
			[ "$Neon_Theme_Keyboard" == "Neon Theme Keyboard" ] || [ "$neon_theme_keyboard" == "neon theme keyboard" ] || \
			[ "$cash_cleaner" == "Cash Cleaner" ] || [ "$Cash_Cleaner" == "cash cleaner" ] || \
			[ "$fast_cleaner" == "Fast Cleaner" ] || [ "$Fast_Cleaner" == "fast clener" ] || \
			[ "$call_skins" == "call skins" ] || [ "$Call_Skins" == "Call Skins" ] || \
			[ "$Funny_Caller" == "Funny Caller" ] || [ "$funny_caller" == "funny caller" ] || \
			[ "$CallME" == "CallMe" ] || [ "$callme" == "callme" ] || \
			[ "$InCall" == "incall" ] || [ "$incall" == "incall" ] || \
			[ "$mycall" == "mycall" ] || [ "$MyCall" == "MyCall" ] || \
			[ "$NewScrean" == "New Screen" ] || [ "$newscrean" == "new screen" ];then

				echo -e "$white$bold $p \t\t\t\t\t\t $red$white [ Malware ] $reset"

		else

				echo -e "$white$bold $p \t\t\t\t\t\t $cyan [ OK ] $reset"
				
		fi
	done


scan_end_time=`date "+%Y/%m/%d-%H:%M:%S"`


echo -e "\n\n$white$bold ========== Scan Info ========== "
echo -e "$white$bold Scan Start Time : $scan_start_time"
echo -e "$white$bold Scan Start Time : $scan_end_time"
echo -e "$white$bold =============================== "

}

info(){

	info_time=`date "+%Y/%m/%d-%H:%M"`

	info_path="/home/$user/L4A/Documents/$info_time"
	if [ -d "$info_path" ];then
		true
	else
		mkdir /home/$user/L4A/Documents/$info_time
	fi

	activity=`adb shell dumpsys activity`
	backup=`adb shell dumpsys audio`
	content=`adb shell dumpsys content`
	connectivity=`adb shell dumpsys connectivity`
	backup=`adb shell dumpsys backup`
	battery=`adb shell dumpsys battery`
	display=`adb shell dumpsys display`
	

	serial=`adb get-serialno`
	echo $activity > $info_path/$serial-Activity.txt
	echo $backup > $info_path/$serial-Backup.txt
	echo $content > $info_path/$serial-Content.txt
	echo $connectivity > $info_path/$serial-Connectivity.txt
	echo $backup > $info_path/$serial-Backup.txt
	echo $battery > $info_path/$serial-Battery.txt
	echo $display > $info_path/$serial-Display.txt
	
	
	echo -e "$white$bold All Data Saved in /home/$user/L4A/Documents"
	echo -e "$white$bold Number of Files Saved in /home/$user/L4A/Documents : 7 "
}




am(){
	echo -e "$white$bold ==================== Meticulously Analyze ==================== \n"
	echo -e "$white$bold In this section, you can view the logs instantly"
	sleep 3
	adb logcat
}



expert(){


	adb shell


}



menu
