#!/usr/bin/bash


## This File Remove all Installed Packages and Folders


sudo rm /usr/bin/AMD

echo "Call File at /usr/bin Directory Removed [ OK ]"

sudo rm -rf /home/$USER/AMD

echo "Main Directory Removed From /opt [ OK ]"

sudo rm -rf /etc/AMD

echo "config File Removed From /etc [ OK ]"

mysql --execute="DROP DATABASE Android_Malware;"



